### ISSUE TITLE
use ulptool error

### ISSUE THREAD

**Issue by savagerex** [duff2013/arduino_ulp#69]
I complie "ulp_README" example. the arduino have this error as below.

I already install esp32 core(1.0.4) and python3.9.

Traceback (most recent call last):
  File "C:\Users\rex.yh.liu\AppData\Local\Arduino15\packages\esp32\tools\ulptool\ulptool-master\esp32ulp_build_recipe.py", line 560, in <module>
    main(sys.argv[1:])
  File "C:\Users\rex.yh.liu\AppData\Local\Arduino15\packages\esp32\tools\ulptool\ulptool-master\esp32ulp_build_recipe.py", line 106, in main
    build_ulp(PATHS, ulp_files, board_options, True)
  File "C:\Users\rex.yh.liu\AppData\Local\Arduino15\packages\esp32\tools\ulptool\ulptool-master\esp32ulp_build_recipe.py", line 137, in build_ulp
    proc = subprocess.Popen(cmd[1],stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=False)
  File "C:\Users\rex.yh.liu\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rex.yh.liu\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] �t�Χ䤣����w���ɮסC
exit status 1

**Comment by savagerex** [comment]
solve it , THX
